name: Build Action

on:
    push:
        branches: [main]

jobs:
    build_action:
        name: Build Action
        permissions:
            contents: write

        runs-on: ubuntu-latest
        steps:
            - name: Setup Node environment
              uses: Exlint/node-environment@v1.2.6
              with:
                  node-version: 18.16.0
                  package-manager: pnpm
                  package-manager-version: 7.32.1

            - name: Create build folder
              run: pnpm build

            - name: Commit build folder
              uses: EndBug/add-and-commit@v9
              with:
                  add: 'build --force'
                  author_name: Exlint
                  author_email: dev@exlint.io
                  message: 'chore: 🤖 Update build folder'
