name: Integration

on:
    pull_request:
        branches: [main]

jobs:
    test_pull_request:
        name: Testing & Checking the code
        runs-on: ubuntu-latest

        steps:
            - name: Setup Node environment
              uses: Exlint/node-environment@v1
              with:
                  node-version: 18.11.0
                  package-manager: pnpm
                  package-manager-version: 7.14.0

            - name: Check unused dependencies
              run: pnpm depcheck

            - name: Check Files and Directories Linter
              run: pnpm inflint

            - name: Check Typescript
              run: pnpm type-check

            - name: Check Prettier
              run: pnpm prettier

            - name: Check ESLint
              run: pnpm lint

            - name: Check build command
              run: pnpm build
