name: Integration

on:
    pull_request:
        branches: [main]

jobs:
    call_pnpm_caching_workflow:
        name: Set pnpm caching
        uses: ./.github/workflows/pnpm-caching.yaml
        with:
            runner: ubuntu-latest
            node-version: 18
            pnpm-version: 7.24.2

    test_depcheck:
        needs: call_pnpm_caching_workflow
        name: Testing Depcheck
        runs-on: ubuntu-latest

        steps:
            - name: Setup Node environment
              uses: Exlint/node-environment@v1.0.4
              with:
                  node-version: 18
                  package-manager: pnpm
                  package-manager-version: 7.24.2

            - name: Test Depcheck
              run: pnpm depcheck

    test_inflint:
        needs: call_pnpm_caching_workflow
        name: Testing Inflint
        runs-on: ubuntu-latest

        steps:
            - name: Setup Node environment
              uses: Exlint/node-environment@v1.0.4
              with:
                  node-version: 18
                  package-manager: pnpm
                  package-manager-version: 7.24.2

            - name: Test Inflint
              run: pnpm inflint

    test_typescript:
        needs: call_pnpm_caching_workflow
        name: Testing TypeScript
        runs-on: ubuntu-latest

        steps:
            - name: Setup Node environment
              uses: Exlint/node-environment@v1.0.4
              with:
                  node-version: 18
                  package-manager: pnpm
                  package-manager-version: 7.24.2

            - name: Test TypeScript
              run: pnpm type-check

    test_eslint:
        needs: call_pnpm_caching_workflow
        name: Testing ESLint
        runs-on: ubuntu-latest

        steps:
            - name: Setup Node environment
              uses: Exlint/node-environment@v1.0.4
              with:
                  node-version: 18
                  package-manager: pnpm
                  package-manager-version: 7.24.2

            - name: Test ESLint
              run: pnpm lint

    test_prettier:
        needs: call_pnpm_caching_workflow
        name: Testing Prettier
        runs-on: ubuntu-latest

        steps:
            - name: Setup Node environment
              uses: Exlint/node-environment@v1.0.4
              with:
                  node-version: 18
                  package-manager: pnpm
                  package-manager-version: 7.24.2

            - name: Test Prettier
              run: pnpm prettier

    test_build:
        needs: call_pnpm_caching_workflow
        name: Testing build
        runs-on: ubuntu-latest

        steps:
            - name: Setup Node environment
              uses: Exlint/node-environment@v1.0.4
              with:
                  node-version: 18
                  package-manager: pnpm
                  package-manager-version: 7.24.2

            - name: Test build
              run: pnpm build
